### ISSUE TITLE
skipped Tests: Chronology

### ISSUE THREAD

**Issue by duncdrum** [StaatsbibliothekBerlin/sbb-relevance-test#35]
`Andreas Gryphus` has many relevant 21st century publication, but the top 20 is 17 of 20 before 1985

**Comment by annekauf** [comment]
not able to find relevant publications with publication date after 2020 - which is the test assertion (1st hit published after 2020)

**Comment by duncdrum** [comment]
Using chronological sorting in an allFields or Titel seach I see: 

- https://stabikat.de/Record/info:doi:10.1017%252Frqx.2022.198
- https://stabikat.de/Record/1795232064 (in Title and in Subject) 2020
- https://stabikat.de/Record/1747791318
- https://stabikat.de/Record/1665420421 (Conference volume about Gryphus) 2020

**Comment by annekauf** [comment]
About half of those examples are published in 2020. Could test be ajusted to "1st hit should be published after 2019"?

**Comment by annekauf** [comment]
Chronology test - therefore test assertion "should contain both primary and secondary literature" doesn't compute. Or put it this way: can't find that assertion as an initial ranking goal...?

**Comment by annekauf** [comment]
Similar: assertion "should show relevant titles in translation" for search all fields "griechische mythologie". Tbd, please. :)

**Comment by duncdrum** [comment]
` .contains(/202\d/)` means `202[0-9]` any digit will work
