### ISSUE TITLE
duplicates `osmanisches reich im …`

### ISSUE THREAD

**Issue by duncdrum** [StaatsbibliothekBerlin/sbb-relevance-test#65]
Die drei Dubletten sind nicht mehr in den Top 100, stark veränderte Trefferliste. Ich würde den test modifizieren. Die neuen Treffer sind aktueller. Die Tatsache das der gleiche Artikel von 2001 3 mal in den TOP20 erschien scheint mir nicht besonders aussagekräftig über die Relevanz der Ergebnisse.                   

@annekauf was meinst Du wenn Du die Trefferlisten vergleichst?

**Comment by annekauf** [comment]
Ohne große Prüfung: ja, d'accord. Gebe das als Frage an den zuständigen Fachreferenten weiter.
