### ISSUE TITLE
Search list divergence 

### ISSUE THREAD

**Issue by annekauf** [StaatsbibliothekBerlin/sbb-relevance-test#76]
Search terms "African American Review" , search index "all fields":
Cypress test yields 29.921 results; typed in search in Ranking1 and search yields 27.551
First hits differ, too.

What's going on?

**Comment by duncdrum** [comment]
the threshold for relevancy changed? One of the Indexfields seems to have a disproportionate impact, if the top hits are affected by the increase in overall hits. The first question id if the new top hits are indeed more relevant to warrant to be on top of the list, which would be an improvement over the live index; if they crowd out other more desirable hits, we need to adjust the boost accordingly.

**Comment by annekauf** [comment]
Question doesn't refer to difference dev - live but to difference WITHIN dev Ranking1: search test via cypress and search via dev frontend search.
Relevance is very clearly better in live system than dev server.

**Comment by annekauf** [comment]
see https://github.com/StaatsbibliothekBerlin/sbb-relevance-test/blob/4ad25736a343eeb1ae40fdcb1fdf62115e2c7b62/cypress/e2e/nested.cy.js#L13
